# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e37cf5632a4e515f8ad2b0af6082d50ffa4075f0c1992ea5d20b96b4777fe0320ea552fe74dd52a28fd3cd9378ebe55dbc1166909659bd77d804762eb6c3c5b
  callbackUrl: 
  glass_client_id: 
  glass_client_secret: 

test:
  secret_key_base: 85d786681cf9b8f34c4a21718662e687f327794ffc179c0c741d1c06cab5eee9214893b57fa3da2a95ee757666ef3c0de2ba55ea16df632635ddef145d7f688f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
